/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 cyberpunk_laptop.glb
Author: Berk Gedik (https://sketchfab.com/berkgedik)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cyberpunk-laptop-concept-design-fddc4e68cc6c498b88b19af1a05bd420
Title: CyberPunk Laptop Concept Design
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useControls } from 'leva';
import { useSpring } from "@react-spring/core";
import { a } from "@react-spring/three";

export function CyberPunkLaptop(props) {
  const { nodes, materials } = useGLTF('/cyberpunk_laptop.glb')
  const [clicked,setClicked] = useState(0)
  //   const { position, rotation } = useSpring({
  //   delay: 1000,
  //   to: {
  //     position: [0, 50.45, -8],
  //     rotation: [-1.6636364746093713, 0, -Math.PI/2]
  //   },
  //   from: {
  //     position: [0, -23.45, 50.89],
  //     rotation: [0, 0, -Math.PI/2 ]
  //   },
  //   config: { mass: 5, tension: 500, friction: 150 }
  // })

  // const {
  //   position,
  //   rotation,
  // } = useControls({
  //   position: {
  //     value: { x: 1, y: 50.45 },
  //     min: -100,
  //     max: 100,
  //     step: 0.1,
  //   },
  //   rotation: {
  //     value: {x:-1.1636364746093713, y:21.231818199158237} ,
  //     min: -Infinity,
  //     max: Infinity,
  //     step: 0.01,
  //   }
  // });
  // <group position={[0, -23.45, 50.89]} rotation={[0, 0, -Math.PI / 2]} scale={100}>
  return (
    <group {...props} dispose={null} onClick={() => setClicked(1)}>
     <group>
      <a.group position={[props.positionScreen.x, props.positionScreen.y, props.positionScreenZ]} rotation={[props.rotationScreen.x, props.rotationScreen.y, props.rotationScreenZ]} scale={100}>
      {/* <a.group position={position} rotation={rotation} scale={100}> */}
        <mesh geometry={nodes.Cube_Auto_04_0.geometry} material={materials.Auto_04} />
      </a.group>
      <mesh geometry={nodes.Cube004_Auto_01_0.geometry} material={materials.Auto_01} position={[props.positionKeyboard.x, props.positionKeyboard.y , props.positionKeyboardZ]} rotation={[props.rotationKeyboard.x, props.rotationKeyboard.y, props.rotationKeyboardZ]} scale={100} />
      {/* <mesh geometry={nodes.Cube007_Auto_01_0.geometry} material={materials.Auto_01} position={[0, -40.16, 75.44]} rotation={[-Math.PI / 2, 0, 0]} scale={100} /> */}
      <mesh geometry={nodes.Keys_Auto_02_0.geometry} material={materials.Auto_02} position={[-72.23, -27.68, 35.45]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      {/* <mesh geometry={nodes.Cube012_Auto_02_0.geometry} material={materials.Auto_02} position={[-91.07, -25.46, 22.76]} rotation={[-Math.PI / 2, 0, 0]} scale={100} /> */}
      {/* <mesh geometry={nodes.Cube018_Auto_02_0.geometry} material={materials.Auto_02} position={[-60.21, -21.79, -5.75]} rotation={[-Math.PI / 2, 0, 0]} scale={100} /> */}
      {/* <mesh geometry={nodes.Cube019_Auto_02_0.geometry} material={materials.Auto_02} position={[-24.73, -21.79, -5.75]} rotation={[-Math.PI / 2, 0, 0]} scale={100} /> */}
      {/* <mesh geometry={nodes.Cube013_Auto_02_0.geometry} material={materials.Auto_02} position={[-91.35, -28.7, 4.17]} rotation={[-Math.PI / 2, 0, 0]} scale={100} /> */}
      {/* <mesh geometry={nodes.Cube005_Auto_03_0.geometry} material={materials.Auto_03} position={[0, -25.59, 7.31]} rotation={[-Math.PI / 2, 0, 0]} scale={100} /> */}
      {/* <mesh geometry={nodes.Cube017_Auto_03_0.geometry} material={materials.Auto_03} position={[100.65, -28.85, 25.18]} rotation={[-Math.PI / 2, 0, 0]} scale={100} /> */}
      {/* <mesh geometry={nodes.Cube001_Auto_03_0.geometry} material={materials.Auto_03} position={[0, 50.45, -8.89]} rotation={[-1.94, 0, 0]} scale={100} /> */}
      {/* <mesh geometry={nodes.BezierCurve001_Auto_03_0.geometry} material={materials.Auto_03} position={[-74.93, -17.34, -70.69]} rotation={[-Math.PI / 2, 0, 0]} scale={100} /> */}
      {/* <mesh geometry={nodes.BezierCurve_Auto_03_0.geometry} material={materials.Auto_03} position={[-74.93, -19.17, -70.69]} rotation={[-Math.PI / 2, 0, 0]} scale={100} /> */}
      {/* <mesh geometry={nodes.BezierCurve002_Auto_03_0.geometry} material={materials.Auto_03} position={[-74.93, -20.54, -70.69]} rotation={[-Math.PI / 2, 0, 0]} scale={100} /> */}
      {/* <mesh geometry={nodes.Cube015_Auto_03_0.geometry} material={materials.Auto_03} position={[-182.23, -22.98, 7.31]} rotation={[-Math.PI / 2, 0, 0]} scale={100} /> */}
      {/* <mesh geometry={nodes.Cube014_Auto_03_0.geometry} material={materials.Auto_03} position={[-182.23, -22.98, 7.31]} rotation={[-Math.PI / 2, 0, 0]} scale={100} /> */}
      {/* <mesh geometry={nodes.Cylinder_Auto_03_0.geometry} material={materials.Auto_03} position={[7.52, 0.85, 2.93]} rotation={[-2.05, 0, 0]} scale={100} /> */}
      {/* <mesh geometry={nodes.Cylinder002_Auto_03_0.geometry} material={materials.Auto_03} position={[-3.49, 0.85, 2.93]} rotation={[-2.05, 0, 0]} scale={100} /> */}
      {/* <mesh geometry={nodes.Cube016_Auto_03_0.geometry} material={materials.Auto_03} position={[-0.6, -11.89, -52.54]} rotation={[2.55, 0.01, -1.58]} scale={100} /> */}
      {/* <mesh geometry={nodes.Cube002_Auto_04_0.geometry} material={materials.Auto_04} position={[0, 50.45, -8.89]} rotation={[-1.94, 0, 0]} scale={100} /> */}
      {/* <mesh geometry={nodes.Cube003_Auto_04_0.geometry} material={materials.Auto_04} position={[0, 50.45, -8.89]} rotation={[-1.94, 0, -Math.PI / 2]} scale={100} /> */}
      <mesh geometry={nodes.Cube020_Auto_04_0.geometry} material={materials.Auto_04} position={[0, 50.45, -8.89]} rotation={[-1.94, 0, -Math.PI / 2]} scale={100} />
    </group>
    </group>
  )
}

useGLTF.preload('/cyberpunk_laptop.glb')
