/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 optimizedContactModel.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function OptimizedContactModel(props) {
  const { nodes, materials } = useGLTF('/optimizedContactModel.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.LeftRoundButtonGlass_low_T_Glass_0.geometry} material={materials['T_Glass.005']} />
        <mesh geometry={nodes.RightRoundButtonGlass_low_T_Glass_0.geometry} material={materials['T_Glass.005']} />
        <mesh geometry={nodes.AudioPlug_low_T_Phone_0.geometry} material={materials['T_Phone.005']} />
        <mesh geometry={nodes.Phone_low_T_Phone_0.geometry} material={materials['T_Phone.005']} />
        <mesh geometry={nodes.Phone_Plug_low_T_Phone_0.geometry} material={materials['T_Phone.005']} />
        <mesh geometry={nodes.PhoneWire_low_T_Phone_0.geometry} material={materials['T_Phone.005']} />
        <mesh geometry={nodes.LeftBottomTurnButton_low_T_Radio_0.geometry} material={materials['T_Radio.005']} />
        <mesh geometry={nodes.LeftHandle_low_T_Radio_0.geometry} material={materials['T_Radio.005']} />
        <mesh geometry={nodes.LeftRoundButton_low_T_Radio_0.geometry} material={materials['T_Radio.005']} />
        <mesh geometry={nodes.MiddleRightTurnButton_low_T_Radio_0.geometry} material={materials['T_Radio.005']} position={[0, 0.01, 0]} />
        <mesh geometry={nodes.MiddleTurnButton_low_T_Radio_0.geometry} material={materials['T_Radio.005']} position={[-0.94, 0.86, 0]} rotation={[0, 0, -0.2]} />
        <mesh geometry={nodes.Needle_low_T_Radio_0.geometry} material={materials['T_Radio.005']} />
        <mesh geometry={nodes.RightBottomTurnButton_low_T_Radio_0.geometry} material={materials['T_Radio.005']} />
        <mesh geometry={nodes.RightRoundButton_low_T_Radio_0.geometry} material={materials['T_Radio.005']} />
        <mesh geometry={nodes.Screen_Protector_low_T_Radio_0.geometry} material={materials['T_Radio.005']} />
        <mesh geometry={nodes.Shell_low_T_Radio_0.geometry} material={materials['T_Radio.005']} />
      </group>
    </group>
  )
}

useGLTF.preload('/optimizedContactModel.glb')
