/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 optimized.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Optimized(props) {
  const { nodes, materials } = useGLTF('./optimized.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.abgVijaHVNRUvcc.geometry} material={materials.UpOvKwLUUXPmnPU} />
        <mesh geometry={nodes.fiqlelggeOoTUAw.geometry} material={materials.SELuppcPLrlTpBi} />
        <mesh geometry={nodes.JtnJKXAEPaOoepM.geometry} material={materials.lbGSuJJwEsUTzIm} />
        <mesh geometry={nodes.NhThIZELXlNUoIr.geometry} material={materials.mpJhsaJJZPPWMEX} />
        <mesh geometry={nodes.RYgQzNzcnFbacQH.geometry} material={materials.VfcxYmbOfnqunYx} />
        <mesh geometry={nodes.zlRXoydEgBQgFUa.geometry} material={materials.zqeFZcIteZtOShc} />
        <mesh geometry={nodes.CpRxqsFibJhVZKA.geometry} material={materials.CGiumILqqSMVyeb} />
        <mesh geometry={nodes.pPCeNYAcgHQGnfB.geometry} material={materials.jRMWtdSAaujlvUA} />
        <mesh geometry={nodes.WeTEPJkcTkMBwBo.geometry} material={materials.lbGSuJJwEsUTzIm} />
        <mesh geometry={nodes.yxTDdMZViYkuOKm.geometry} material={materials.BczvixNfkWQzRzZ} />
        <mesh geometry={nodes.eAcvqfZlEdoxHsj.geometry} material={materials.IlNnjEDxsExlBOr} />
        <mesh geometry={nodes.guoofBSjCEiTIJr.geometry} material={materials.JjuwNKnMBUdtRLb} />
        <mesh geometry={nodes.NWErafhynAfYQEz.geometry} material={materials.pZbDFXVUkfRwjmQ} />
        <mesh geometry={nodes.piXptsgcOfaGWrM.geometry} material={materials.WLATjirhQCUYAAG} />
        <mesh geometry={nodes.QFFLzaWPRnuQYJR.geometry} material={materials.hPcehRUjcLAosED} />
        <mesh geometry={nodes.QMBrsnrwfcVKELm.geometry} material={materials.VqwNZwmDotIMflD} />
        <mesh geometry={nodes.QYMcPaZnXQfyXcJ.geometry} material={materials.NQXltfOcKPZPQdI} />
        <mesh geometry={nodes.RjGOdbHqvxkiDns.geometry} material={materials.lbGSuJJwEsUTzIm} />
        <mesh geometry={nodes.RkSurqpnfNMQZfv.geometry} material={materials.zWLcvvnJhbcTEtJ} />
        <mesh geometry={nodes.VqfccLWHjnpnmIO.geometry} material={materials.BMKLbAPYqPmfArt} />
        <mesh geometry={nodes.WPFmzKypKbUYgQT.geometry} material={materials.lbGSuJJwEsUTzIm} />
        <mesh geometry={nodes.YJMoQnvBNpTrgeH.geometry} material={materials.PCfVLhSpFVCvRmc} />
      </group>
    </group>
  )
}

useGLTF.preload('/optimized.gltf')
