/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 contact.glb
Author: PjotrCleys (https://sketchfab.com/PjotrCleys)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/1960s-army-signal-corps-radio-receiver-4985d0f47ca8444f9d85d96b4d9f4a98
Title: 1960s Army Signal Corps Radio Receiver.
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/contact.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Phone_low_T_Phone_0.geometry} material={materials.T_Phone} />
        <mesh geometry={nodes.PhoneWire_low_T_Phone_0.geometry} material={materials.T_Phone} />
        <mesh geometry={nodes.Phone_Plug_low_T_Phone_0.geometry} material={materials.T_Phone} />
        <mesh geometry={nodes.AudioPlug_low_T_Phone_0.geometry} material={materials.T_Phone} />
        <mesh geometry={nodes.RightRoundButtonGlass_low_T_Glass_0.geometry} material={materials.T_Glass} />
        <mesh geometry={nodes.Screen_Glass_low_T_Glass_0.geometry} material={materials.T_Glass} />
        <mesh geometry={nodes.LeftRoundButtonGlass_low_T_Glass_0.geometry} material={materials.T_Glass} />
        <mesh geometry={nodes.RightRoundButton_low_T_Radio_0.geometry} material={materials.T_Radio} />
        <mesh geometry={nodes.LeftRoundButton_low_T_Radio_0.geometry} material={materials.T_Radio} />
        <mesh geometry={nodes.Needle_low_T_Radio_0.geometry} material={materials.T_Radio} />
        <mesh geometry={nodes.Left_Metal_Extrusion_low_T_Radio_0.geometry} material={materials.T_Radio} position={[-19.17, 0, 0.01]} />
        <mesh geometry={nodes.RightBottomTurnButton_low_T_Radio_0.geometry} material={materials.T_Radio} />
        <mesh geometry={nodes.ScreenBack_low_T_Radio_0.geometry} material={materials.T_Radio} />
        <mesh geometry={nodes.Screen_Protector_low_T_Radio_0.geometry} material={materials.T_Radio} />
        <mesh geometry={nodes.Right_Metal_Extrusion_low_T_Radio_0.geometry} material={materials.T_Radio} />
        <mesh geometry={nodes.MiddleTurnButton_low_T_Radio_0.geometry} material={materials.T_Radio} position={[-0.94, 0.86, 0]} rotation={[0, 0, -0.2]} />
        <mesh geometry={nodes.MiddleRightTurnButton_low_T_Radio_0.geometry} material={materials.T_Radio} position={[0, 0.01, 0]} />
        <mesh geometry={nodes.Screws_low_T_Radio_0.geometry} material={materials.T_Radio} />
        <mesh geometry={nodes.LeftBottomTurnButton_low_T_Radio_0.geometry} material={materials.T_Radio} />
        <mesh geometry={nodes.Back_Lid_low_T_Radio_0.geometry} material={materials.T_Radio} />
        <mesh geometry={nodes.Right_MetalHolder_low_T_Radio_0.geometry} material={materials.T_Radio} />
        <mesh geometry={nodes.Left_MetalHolder_low_T_Radio_0.geometry} material={materials.T_Radio} />
        <mesh geometry={nodes.RightHandle_low_T_Radio_0.geometry} material={materials.T_Radio} />
        <mesh geometry={nodes.Shell_low_T_Radio_0.geometry} material={materials.T_Radio} />
        <mesh geometry={nodes.LeftHandle_low_T_Radio_0.geometry} material={materials.T_Radio} />
      </group>
    </group>
  )
}

useGLTF.preload('/contact.glb')
