import { useControls } from 'leva'

const {
  scaleLaptop,
  positionLaptop,
  positionLaptopZ,
  rotationLaptop,
  rotationLaptopZ,
  positionScreen,
  positionScreenZ,
  rotationScreen,
  rotationScreenZ,
  positionKeyboard,
  positionKeyboardZ,
  rotationKeyboard,
  rotationKeyboardZ,
  typeWriterPosition,
  typeWriterRotation,
} = useControls({
  rotationKeyboard: {
    value: { x: -Math.PI / 2, y: 0 },
    min: -Infinity,
    max: Infinity,
    step: 0.01,
  },
  rotationKeyboardZ: {
    value: 0,
    min: -Infinity,
    max: Infinity,
    step: 0.01,
  },
  positionKeyboard: {
    value: { x: 0, y: -25.59 },
    min: -100,
    max: 100,
    step: 0.1,
  },
  positionKeyboardZ: {
    value: 7.31,
    min: -10,
    max: 10,
    step: 0.01,
  },
  scaleLaptop: {
    value: 10,
    min: -10,
    max: 10,
    step: 0.001,
  },
  positionLaptop: {
    value: { x: 0, y: 0 },
    min: -10,
    max: 10,
    step: 0.1,
  },
  positionLaptopZ: {
    value: 0,
    min: -10,
    max: 10,
    step: 0.1,
  },
  rotationLaptopZ: {
    value: 0,
    min: -10,
    max: 10,
    step: 0.01,
  },
  rotationLaptop: {
    value: { x: 0, y: 0 },
    min: -Infinity,
    max: Infinity,
    step: 0.01,
  },
  positionScreen: {
    value: { x: 0, y: 50.45 },
    min: -Infinity,
    max: Infinity,
    step: 0.1,
  },
  rotationScreen: {
    value: { x: -1.94, y: 0 },
    min: -Infinity,
    max: Infinity,
    step: 0.001,
  },
  rotationScreenZ: {
    value: -Math.PI / 2,
    min: -Infinity,
    max: Infinity,
    step: 0.001,
  },
  positionScreenZ: {
    value: -8.89,
    min: -100,
    max: 100,
    step: 0.1,
  },
  typeWriterPosition: {
    value: { x: -0.3600000000000022, y: 1.8539999999999968 },
    min: -100,
    max: 100,
    step: 0.01,
  },
  typeWriterRotation: {
    value: { x: 0, y: 0 },
    min: -100,
    max: 100,
    step: 0.01,
  },
})
